services:  
  web:
    volumes:
      - ./logs/:/logs/:delegated
    build: .
    ports:
      - "80:80"
    environment:
      REDIS_ADDRESS: "redis:6379"    
    image: escape-server:latest
  redis:
    image: "redis:alpine"